config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/failure'

  resources :friend_requests
  devise_for :user

	root 'homes#index'
	root 'conversations#index'
	resources :conversations, only: [:index, :show]
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :friendships
	resources :users, only: [:index]
	resources :profiles
	resources :friends
	resources :requests
	resources :personal_messages

	get 'homes/index'
	#get '/auth/:provider/callback', :to => 'sessions#facebook',  via: [:get, :post]
	match 'auth/:provider/callback', to: 'sessions#create',  via: [:get, :post]
	match '/auth/failure', :to => 'sessions#failure',  via: [:get, :post]
	
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord

	 belongs_to :user
  def self.from_omniauth(auth)
    authenticate = where(provider: auth['provider'], :uid=>auth['uid']).first_or_initialize
    if authenticate.user
      authenticate.provider = auth.provider
      authenticate.uid = auth.uid
      authenticate.token = auth.credentials.token
    else
      user = User.find_by_email(auth.info.email)
      unless user
          user = User.new
        end
          authenticate.provider = auth.provider
        authenticate.uid = auth.uid
        authenticate.token = auth.credentials.token
        user.email = auth.info.email
        if auth['provider'] == "twitter"
          user.email = auth.extra.raw_info.id.to_s+"@twitter.com"
        end
        user.password =  Devise.friendly_token.first(8)
        user.save!
        authenticate.user_id = user.id
     end
    authenticate.save
    authenticate.user
  end
end

app/models/conversation.rb
class Conversation < ApplicationRecord

	belongs_to :author, class_name: 'User'
  belongs_to :receiver, class_name: 'User'

  has_many :personal_messages, -> { order(created_at: :asc) }, dependent: :destroy

  validates :author, presence: true

  scope :participating, -> (user) do
    where("(conversations.author_id = ? OR conversations.receiver_id = ?)", user.id, user.id)
  end

  scope :between, -> (sender_id, receiver_id) do
    where(author_id: sender_id, receiver_id: receiver_id).or(where(author_id: receiver_id, receiver_id: sender_id))
  end

  def with(current_user)
    author == current_user ? receiver : author
  end

  def participates?(user)
    author == user || receiver == user
  end
end  

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
	 validates :name, uniqueness: true
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  def accept
    user.friends << friend
    destroy
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  #after_create :create_inverse_relationship
 # after_destroy :destroy_inverse_relationship

  belongs_to :user
  belongs_to :friend, class_name: 'User'

 # private

  #def create_inverse_relationship
  #  friend.friendships.create(friend: user)
  #end

 # def destroy_inverse_relationship
  #  friendship = friend.friendships.find_by(friend: user)
  #  friendship.destroy if friendship
  #end
end

app/models/personal_message.rb
class PersonalMessage < ApplicationRecord
 belongs_to :conversation
  belongs_to :user

  validates :body, presence: true
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/request.rb
class Request < ApplicationRecord
	 belongs_to :user
  belongs_to :friend, class_name: 'User'

   def accept
    user.friends << friend
    destroy
  end
end

app/models/user.rb
class User < ApplicationRecord


	mount_uploader :image, AvatarUploader
	has_friendship
  has_many :incoming_friend_requests,
   class_name: 'FriendRequest',
   source: :friend

	# before_create :confirmation_token

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :authored_conversations, class_name: 'Conversation', foreign_key: 'author_id'
  has_many :received_conversations, class_name: 'Conversation', foreign_key: 'received_id'

  has_many :personal_messages, dependent: :destroy

  def name
    email.split('@')[0]
  end

  has_many :authentications, dependent: :destroy
	

	has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships, dependent: :destroy
 	has_many :friend_requests, dependent: :destroy
  # has_many :pending_friends, through: :friend_requests, source: :friend, dependent: :destroy
	has_many :received_friendships, class_name: "Friendship", foreign_key: "friend_id"
	has_many :active_friends, -> { where(friendships: { accepte: true}) }, through: :friendships, source: :friend
	has_many :received_friends, -> { where(friendships: { accepte: true}) }, through: :received_friendships, source: :user, dependent: :destroy
	# has_many :pending_friends, -> { where(friendships: { accepte: false}) }, through: :friendships, source: :friend
	has_many :requested_friendships, -> { where(friendships: { accepte: false}) }, through: :received_friendships, source: :user
	
	# to call all your friends
	def friends
	  active_friends | received_friends
	end

	# to call your pending sent or received
	def pending
		pending_friends | requested_friendships
	end

	def pending_friends
		Friendship.where(friend_id: self.id, accepte: false)
	end

	def accepted_friends
		Friendship.where(friend_id: self.id, accepte: true)
	end

	def remove_friend(friend)
    current_user.friends.destroy(friend)
  end
	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

	def index
  end

  def blog
  end


end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

	def new
		@profile = Profile.new
	end

	def create
		@profile = Profile.new(name: params[:profile][:name], image: params[:profile][:image], email: params[:profile][:email], about: params[:profile][:about])
		@profile.save
		redirect_to profiles_path(@profile)
	end

	def show
		@profile = Profile.find(params[:id])
	end

	def index
		@profile = Profile.all
	end

	def edit
		@profile = Profile.find(params[:id])
	end

	def update
		@profile = Profile.find(params[:id])
		if @profile.update(name: params[:profile][:name], image: params[:profile][:image], email: params[:profile][:email], about: params[:profile][:about])
			redirect_to profile_path(@profile)
		else
			render 'edit'
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversation_helper.rb
module ConversationHelper
end

app/helpers/frendships_helper.rb
module FrendshipsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shared_helper.rb
module SharedHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>
 
<%= form_for :profile, url: profile_path(@profile), method: :patch do |f| %>
 
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@profile.errors.count, "error") %> prohibited
        this profile from being saved:
      </h2>
      <ul>
        <% @profile.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
 <div class="form-group">
    <label class="col-sm-2 control-label">Name:</label>
    <div class="col-sm-2  inputGroupContainer">
      <%= f.text_field :name,:class=>"form-control",:placeholder => "First name" %>
    </div>
  </div>
 

 <div class="form-group">
    <label class="col-sm-1 control-label">Email:</label>
    <div class="col-sm-3  inputGroupContainer">
      <%= f.text_field :email,:class=>"form-control",:placeholder => "Email" %>
    </div>
  </div>

 <div class="form-group">
    <label class="col-sm-1 control-label">About:</label>
    <div class="col-sm-3  inputGroupContainer">
      <%= f.text_field :about,:class=>"form-control",:placeholder => "About" %>
    </div>
  </div><br><br><br>
  

  <div class="form-group">
      <label class="col-sm-1 control-label">Image:</label>
    <div class="col-sm-1  inputGroupContainer">
     <%= f.file_field :image,:onchange => "showimagepreview(this)",:class=>"img_file"  %>
     <img id="imgprvw" style="width: 167px; height: 94px; margin-top: 8px;" />
    </div>
  </div>

  <p>
    <%= f.submit 'save', class: "btn btn-info" %>
  </p>

app/views/profiles/index.html.erb
<h2> My Profile <h2>
  <tr>
    <th>Name:</th><br>
    <th>Email:</th><br>
    <th>Image:</th><br>
    <th>About:</th><br>      
  </tr>
 
  <% @profile.each do |profile|%>
    <tr>
    <% if current_user_signed_in? %>
      <td><%= profile.name %></td><br>
      <td><%= profile.email %></td><br>
      <td><img src="<%= profile.image %>" style="height: 120px; width: 150px;"></td><br><br><br><br><br><br>
      <td><%= profile.about %></td>
     <td><%= link_to 'Edit', edit_profile_path(profile), class: "btn btn-primary" %></td>
       <% end %>
  <% end %>
   <%= link_to 'Back', root_path, class: "btn btn-info" %>

   <%= render partial: "users/background"%>

app/views/profiles/new.html.erb
<%= form_for @profile, url: profiles_path, method: 'post' do |f| %>

  <div class="form-group">
    <label class="col-sm-2 control-label">Name:</label>
    <div class="col-sm-2  inputGroupContainer">
      <%= f.text_field :name,:class=>"form-control",:placeholder => "First name" %>
    </div>
  </div>
 

 <div class="form-group">
    <label class="col-sm-1 control-label">Email:</label>
    <div class="col-sm-3  inputGroupContainer">
      <%= f.text_field :email,:class=>"form-control",:placeholder => "Email" %>
    </div>
  </div>

 <div class="form-group">
    <label class="col-sm-1 control-label">About:</label>
    <div class="col-sm-3  inputGroupContainer">
      <%= f.text_field :about,:class=>"form-control",:placeholder => "About" %>
    </div>
  </div><br><br><br>
  

  <div class="form-group">
      <label class="col-sm-1 control-label">Image:</label>
    <div class="col-sm-1  inputGroupContainer">
     <%= f.file_field :image,:onchange => "showimagepreview(this)",:class=>"img_file"  %>
     <img id="imgprvw" style="width: 167px; height: 94px; margin-top: 8px;" />
    </div>
  </div>

  <p>
    <%= f.submit 'save', class: "btn btn-info" %>
  </p>

  <%= link_to 'Back', users_path, class: "btn btn-info" %>

<% end %>

app/views/profiles/show.html.erb
 <% if current_user_signed_in? %>
 <div class="form-group">
    <label class="col-sm-2 control-label">Name:</label>
    <div class="col-sm-2  inputGroupContainer">
      <%= f.text_field :name,:class=>"form-control",:placeholder => "First name" %>
    </div>
  </div>
 

 <div class="form-group">
    <label class="col-sm-1 control-label">Email:</label>
    <div class="col-sm-3  inputGroupContainer">
      <%= f.text_field :email,:class=>"form-control",:placeholder => "Email" %>
    </div>
  </div>

 <div class="form-group">
    <label class="col-sm-1 control-label">About:</label>
    <div class="col-sm-3  inputGroupContainer">
      <%= f.text_field :about,:class=>"form-control",:placeholder => "About" %>
    </div>
  </div><br><br><br>
  

  <div class="form-group">
    <label class="col-sm-1 control-label">Image:</label>
    <div class="col-sm-1  inputGroupContainer">
     <%= f.file_field :image,:onchange => "showimagepreview(this)",:class=>"img_file"  %>
     <img id="imgprvw" style="width: 167px; height: 94px; margin-top: 8px;" />
    </div>
  </div>