config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/failure'

  resources :friend_requests
  devise_for :user

	root 'homes#index'
	root 'conversations#index'
	resources :conversations, only: [:index, :show]
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :friendships
	resources :users, only: [:index]
	resources :profiles
	resources :friends
	resources :requests
	resources :personal_messages

	get 'homes/index'
	#get '/auth/:provider/callback', :to => 'sessions#facebook',  via: [:get, :post]
	match 'auth/:provider/callback', to: 'sessions#create',  via: [:get, :post]
	match '/auth/failure', :to => 'sessions#failure',  via: [:get, :post]
	
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord

	 belongs_to :user
  def self.from_omniauth(auth)
    authenticate = where(provider: auth['provider'], :uid=>auth['uid']).first_or_initialize
    if authenticate.user
      authenticate.provider = auth.provider
      authenticate.uid = auth.uid
      authenticate.token = auth.credentials.token
    else
      user = User.find_by_email(auth.info.email)
      unless user
          user = User.new
        end
          authenticate.provider = auth.provider
        authenticate.uid = auth.uid
        authenticate.token = auth.credentials.token
        user.email = auth.info.email
        if auth['provider'] == "twitter"
          user.email = auth.extra.raw_info.id.to_s+"@twitter.com"
        end
        user.password =  Devise.friendly_token.first(8)
        user.save!
        authenticate.user_id = user.id
     end
    authenticate.save
    authenticate.user
  end
end

app/models/conversation.rb
class Conversation < ApplicationRecord

	belongs_to :author, class_name: 'User'
  belongs_to :receiver, class_name: 'User'

  has_many :personal_messages, -> { order(created_at: :asc) }, dependent: :destroy

  validates :author, presence: true

  scope :participating, -> (user) do
    where("(conversations.author_id = ? OR conversations.receiver_id = ?)", user.id, user.id)
  end

  scope :between, -> (sender_id, receiver_id) do
    where(author_id: sender_id, receiver_id: receiver_id).or(where(author_id: receiver_id, receiver_id: sender_id))
  end

  def with(current_user)
    author == current_user ? receiver : author
  end

  def participates?(user)
    author == user || receiver == user
  end
end  

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
	 validates :name, uniqueness: true
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  def accept
    user.friends << friend
    destroy
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  #after_create :create_inverse_relationship
 # after_destroy :destroy_inverse_relationship

  belongs_to :user
  belongs_to :friend, class_name: 'User'

 # private

  #def create_inverse_relationship
  #  friend.friendships.create(friend: user)
  #end

 # def destroy_inverse_relationship
  #  friendship = friend.friendships.find_by(friend: user)
  #  friendship.destroy if friendship
  #end
end

app/models/personal_message.rb
class PersonalMessage < ApplicationRecord
 belongs_to :conversation
  belongs_to :user

  validates :body, presence: true
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/request.rb
class Request < ApplicationRecord
	 belongs_to :user
  belongs_to :friend, class_name: 'User'

   def accept
    user.friends << friend
    destroy
  end
end

app/models/user.rb
class User < ApplicationRecord


	mount_uploader :image, AvatarUploader
	has_friendship
  has_many :incoming_friend_requests,
   class_name: 'FriendRequest',
   source: :friend

	# before_create :confirmation_token

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :authored_conversations, class_name: 'Conversation', foreign_key: 'author_id'
  has_many :received_conversations, class_name: 'Conversation', foreign_key: 'received_id'

  has_many :personal_messages, dependent: :destroy

  def name
    email.split('@')[0]
  end

  has_many :authentications, dependent: :destroy
	

	has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships, dependent: :destroy
 	has_many :friend_requests, dependent: :destroy
  # has_many :pending_friends, through: :friend_requests, source: :friend, dependent: :destroy
	has_many :received_friendships, class_name: "Friendship", foreign_key: "friend_id"
	has_many :active_friends, -> { where(friendships: { accepte: true}) }, through: :friendships, source: :friend
	has_many :received_friends, -> { where(friendships: { accepte: true}) }, through: :received_friendships, source: :user, dependent: :destroy
	# has_many :pending_friends, -> { where(friendships: { accepte: false}) }, through: :friendships, source: :friend
	has_many :requested_friendships, -> { where(friendships: { accepte: false}) }, through: :received_friendships, source: :user
	
	# to call all your friends
	def friends
	  active_friends | received_friends
	end

	# to call your pending sent or received
	def pending
		pending_friends | requested_friendships
	end

	def pending_friends
		Friendship.where(friend_id: self.id, accepte: false)
	end

	def accepted_friends
		Friendship.where(friend_id: self.id, accepte: true)
	end

	def remove_friend(friend)
    current_user.friends.destroy(friend)
  end
	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
	 before_action :set_friend, only: :destroy
	def new
		@friend = Friend.new
	end

	def create
		@friend = Friend.new(name: params[:friend][:name], image: params[:friend][:image], email: params[:friend][:email], about: params[:friend][:about])
		@friend.save
		redirect_to friends_path(@friend)
	end

	def show
		@friendship = User.find(params[:id])
	end

	def index
		@friend = current_user.friends
	end

	def friend
		user = current_user
		@users = user.friends
	end

	def friendprofile
		@friendship = User.find(params[:id])
	end

  private
	def set_friend
	  @friend = current_user.friends.find(params[:id])
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

	def index
  end

  def blog
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversation_helper.rb
module ConversationHelper
end

app/helpers/frendships_helper.rb
module FrendshipsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shared_helper.rb
module SharedHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friends/friendprofile.html.erb
<html>
<body><br><br>
	<table border="2px" align="center" width="30%", style="background-color: pink">
	<td>
<center><h1>Friend Profile </h1></center>
 <ul>

<hr> <strong>Name:</strong>
    <%= @friendship.name %><br><br>
	 <strong>Email:</strong>
	<%= @friendship.email %><br><br>
     <strong>Image</strong>
	<a href="friendimage"><%= image_tag @friendship.image_url.to_s, style:"height: 70px; width: 100px;" %></a><br><br>
    <strong>About:</strong>
    <%= @friendship.about %><br><br>
</ul> 

</td>
</table><br>
<center><%= link_to 'Back', :back, class: "btn btn-success btn-lg" %></center>

</body>
</html>



<style type="text/css">
body{
  background-color: lightcyan;
  background-image: url(/assets/19.jpg);
  background-position: center center;
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: cover;
  }
  .dropdown-menu li:hover{
  visibility: visible;
  }
  .dropdown:hover .dropdown-menu{
    display: block;
  }
  .dropdown-menu > li > a:hover, .dropdown-menu > li > a:focus{
    background-color: #ffba98;
  }
 
</style>

app/views/friends/index.html.erb
<!DOCTYPE html>
 <html>
 <body>
 <center><h1>My Friends </h1></center>
<table class="table">
 <ul>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Profile Image</th>
    <th>About</th>
  </tr>
<% @friend.each do |friend| %>
  <tr>
    <td><%= friend.name %> </td>
    <td><%= friend.email %></td>
    <td><%= image_tag friend.image_url.to_s, style:"height: 70px; width: 100px;" %></td>
    <td><%= friend.about %></td>
     
    <td> <%= link_to 'Show profile',friend_path(friend), class: "btn btn-success "%> </td> 
    <td>
      <% if friend.friendships.present?%>
        <% friend.friendships.each do |friend| %>
          <%= link_to "Unfriend", friendship_path(id: friend.id), method: :delete, class: "btn btn-danger" %>
        <%end%>   
      <%end%>
    </td> 
  </tr>
 <%end%> 
</ul>
</table>
</body>
</html>


<center><%= link_to 'Back', users_path, class: "btn btn-success btn-lg" %></center><br><br>


<%= render partial: "users/background"%>

app/views/friends/show.html.erb
<html>
<body><br><br>
	<table border="2px" align="center" width="30%", style="background-color: pink">
	<td>
<center><h1>Friend Profile </h1></center>
 <ul>
<hr> <strong>Name:</strong>
 <%= @friendship.name %><br><br>
  <strong>Email:</strong>
 <%= @friendship.email %><br><br>
  <strong>Image</strong>
 <a href="friendimage"><%= image_tag @friendship.image_url.to_s, style:"height: 70px; width: 100px;" %></a><br><br>
  <strong>About:</strong>
 <%= @friendship.about %><br><br>
 </hr>
</ul> 
</td>
</table><br>
</body>
</html>

<center><%= link_to 'Back', :back, class: "btn btn-success btn-lg" %></center>



<%= render partial: "users/background"%>