config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/failure'

  resources :friend_requests
  devise_for :user

	root 'homes#index'
	root 'conversations#index'
	resources :conversations, only: [:index, :show]
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :friendships
	resources :users, only: [:index]
	resources :profiles
	resources :friends
	resources :requests
	resources :personal_messages

	get 'homes/index'
	#get '/auth/:provider/callback', :to => 'sessions#facebook',  via: [:get, :post]
	match 'auth/:provider/callback', to: 'sessions#create',  via: [:get, :post]
	match '/auth/failure', :to => 'sessions#failure',  via: [:get, :post]
	
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord

	 belongs_to :user
  def self.from_omniauth(auth)
    authenticate = where(provider: auth['provider'], :uid=>auth['uid']).first_or_initialize
    if authenticate.user
      authenticate.provider = auth.provider
      authenticate.uid = auth.uid
      authenticate.token = auth.credentials.token
    else
      user = User.find_by_email(auth.info.email)
      unless user
          user = User.new
        end
          authenticate.provider = auth.provider
        authenticate.uid = auth.uid
        authenticate.token = auth.credentials.token
        user.email = auth.info.email
        if auth['provider'] == "twitter"
          user.email = auth.extra.raw_info.id.to_s+"@twitter.com"
        end
        user.password =  Devise.friendly_token.first(8)
        user.save!
        authenticate.user_id = user.id
     end
    authenticate.save
    authenticate.user
  end
end

app/models/conversation.rb
class Conversation < ApplicationRecord

	belongs_to :author, class_name: 'User'
  belongs_to :receiver, class_name: 'User'

  has_many :personal_messages, -> { order(created_at: :asc) }, dependent: :destroy

  validates :author, presence: true

  scope :participating, -> (user) do
    where("(conversations.author_id = ? OR conversations.receiver_id = ?)", user.id, user.id)
  end

  scope :between, -> (sender_id, receiver_id) do
    where(author_id: sender_id, receiver_id: receiver_id).or(where(author_id: receiver_id, receiver_id: sender_id))
  end

  def with(current_user)
    author == current_user ? receiver : author
  end

  def participates?(user)
    author == user || receiver == user
  end
end  

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
	 validates :name, uniqueness: true
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  def accept
    user.friends << friend
    destroy
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  #after_create :create_inverse_relationship
 # after_destroy :destroy_inverse_relationship

  belongs_to :user
  belongs_to :friend, class_name: 'User'

 # private

  #def create_inverse_relationship
  #  friend.friendships.create(friend: user)
  #end

 # def destroy_inverse_relationship
  #  friendship = friend.friendships.find_by(friend: user)
  #  friendship.destroy if friendship
  #end
end

app/models/personal_message.rb
class PersonalMessage < ApplicationRecord
 belongs_to :conversation
  belongs_to :user

  validates :body, presence: true
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/request.rb
class Request < ApplicationRecord
	 belongs_to :user
  belongs_to :friend, class_name: 'User'

   def accept
    user.friends << friend
    destroy
  end
end

app/models/user.rb
class User < ApplicationRecord


	mount_uploader :image, AvatarUploader
	has_friendship
  has_many :incoming_friend_requests,
   class_name: 'FriendRequest',
   source: :friend

	# before_create :confirmation_token

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :authored_conversations, class_name: 'Conversation', foreign_key: 'author_id'
  has_many :received_conversations, class_name: 'Conversation', foreign_key: 'received_id'

  has_many :personal_messages, dependent: :destroy

  def name
    email.split('@')[0]
  end

  has_many :authentications, dependent: :destroy
	

	has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships, dependent: :destroy
 	has_many :friend_requests, dependent: :destroy
  # has_many :pending_friends, through: :friend_requests, source: :friend, dependent: :destroy
	has_many :received_friendships, class_name: "Friendship", foreign_key: "friend_id"
	has_many :active_friends, -> { where(friendships: { accepte: true}) }, through: :friendships, source: :friend
	has_many :received_friends, -> { where(friendships: { accepte: true}) }, through: :received_friendships, source: :user, dependent: :destroy
	# has_many :pending_friends, -> { where(friendships: { accepte: false}) }, through: :friendships, source: :friend
	has_many :requested_friendships, -> { where(friendships: { accepte: false}) }, through: :received_friendships, source: :user
	
	# to call all your friends
	def friends
	  active_friends | received_friends
	end

	# to call your pending sent or received
	def pending
		pending_friends | requested_friendships
	end

	def pending_friends
		Friendship.where(friend_id: self.id, accepte: false)
	end

	def accepted_friends
		Friendship.where(friend_id: self.id, accepte: true)
	end

	def remove_friend(friend)
    current_user.friends.destroy(friend)
  end
	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

	def index
  end

  def blog
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(name: params[:user][:name], image: params[:user][:image], email: params[:user][:email], about: params[:user][:about])
		@user.save
		redirect_to users_path(@user)
	end

	def show
		@user = User.find(params[:id])
	end

	def index
		if params[:name].present?
	   @user = User.where("name like ?", "%#{params[:name]}%")
	  else
	   @user = User.all
	  end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to users_path
	end

	def destroy
	  current_user.remove_friend(@friend)
	  head :no_content
  end

	def myfrnd
		user = current_user
		@users = user.friends
	end

	 def omniauth_failure
    redirect_to init_sign_in_users_path
    #redirect wherever you want.
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversation_helper.rb
module ConversationHelper
end

app/helpers/frendships_helper.rb
module FrendshipsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shared_helper.rb
module SharedHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_background.html.erb
<style type="text/css">
  body{
    background-color: lightcyan;
    background-image: url(/assets/19.jpg);
    background-position: center center;
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
    }
    .dropdown-menu li:hover{
    visibility: visible;
    }
    .dropdown:hover .dropdown-menu{
      display: block;
    }
    .dropdown-menu > li > a:hover, .dropdown-menu > li > a:focus{
      background-color: #ffba98;
    }
</style>

app/views/users/_user.html.erb
  <% @user.where.not(id: current_user.id).each do |user| %>
<li>
  <h1 style="color:red;"> <%= user.name %> </h1>| <%= link_to 'send a message', new_personal_message_path(receiver_id: user) %>
</li>
<% end %>

app/views/users/index.html.erb
<h1>All Users</h1>

<td><%= link_to 'My Profile', friendships_path, class: "btn btn-primary"  %> </td><br><br>

 <%= form_for :user, url: users_path, :method => 'get' do |f| %>
  <p>
   <%= text_field_tag :name %>
   <%= submit_tag 'Search' , class: "btn btn-primary" %>
  </p>
 <% end %>

<table>
  <tr>
    <th>Name</th>
     <th colspan="1"></th>      
    <th>Email</th>
    <th colspan="2"></th>
    <th>Image</th>
    <th colspan="3"></th>
    <th>About</th>
  </tr>


  <% @user.where.not(id: current_user.id).each do |user| %>
    <tr>
     <td> <%= user.name %> <br> 
     |<%= link_to 'send a message', new_personal_message_path(receiver_id: user) %></td>
      <th colspan="2"></th>
      <td><%= user.email %></td>
      <th colspan="2"></th>
      <td><img src="<%= user.image %>" style="height: 120px; width: 150px;"></td>
      <th colspan="3"></th>
      <td><%= user.about %></td>
      <td>
       <p align="right">
      <%if Friendship.where(user_id: [current_user.id, user.id],friend_id: [current_user.id, user.id],accepte: false).present?%>
         <button type="button" class="btn btn-danger">Request sent</button>
        <%elsif Friendship.where(user_id: [current_user.id, user.id],friend_id: [current_user.id, user.id],accepte: true).present? %>
         <button type="button" class="btn btn-primary">Friend</button>
        <%else %> 
         <%= link_to "Add Friend", friendships_path(friend_id: user.id), method: :post, class: "btn btn-success"%>
        <%if current_user && current_user.try(:admin?)%>
         <%= link_to "Delete", user_path(id: user.id), method: :delete, class: "btn btn-danger"%>
        <% end %> 
      <%end%>
      </p>
      </td>
    </tr>
  <% end %>
  <%= link_to 'Back', root_path, class: "btn btn-success btn-md" %>

  <%= render partial: "users/background"%>